<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<PackageIcon>icon.png</PackageIcon>
		<Title>Naminari.Auto</Title>
		<PackageId>Naminari.Auto</PackageId>
		<Authors>Khang152</Authors>
		<Company>iRaidenStudio</Company>
		<Description>Naminari.Auto is a library designed to simplify task automation by providing users with the ability to control their mouse and keyboard inputs. With Naminari.Auto, you can easily create scripts that simulate user input without the need for manual input.</Description>
		<Copyright>Copyright (c) 2024</Copyright>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/Khang152/Naminari.Auto</PackageProjectUrl>
		<PackageTags>Automation Bot Script Auto Mouse Keyboard</PackageTags>
		<RepositoryUrl>https://github.com/Khang152/Naminari.Auto.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DebugType>embedded</DebugType>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
		<None Include="..\.editorconfig" Link=".editorconfig" />
		<None Include="Images\icon.ico" Pack="true" PackagePath="\" />
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0.20240616" />
		<PackageReference Include="OpenCvSharp4.Windows" Version="4.10.0.20240616" />
	</ItemGroup>
</Project>
